version: '3.7'

services:
  kra-minio:
    build:
      context: ./config/minio/
      dockerfile: Dockerfile
    container_name: kra-minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_data:/data
    networks:
      - app-network

networks:
  app-network:
    name: kra-network
    driver: bridge
