# Generated by Django 5.1.5 on 2025-03-14 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата завершения')),
            ],
            options={
                'verbose_name': 'семестр',
                'verbose_name_plural': 'семестры',
            },
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('subgroup_type', models.CharField(choices=[('b', 'Бакалавриат'), ('m', 'Магистратура'), ('s', 'Специалитет')], max_length=1, verbose_name='Тип учебной группы')),
            ],
            options={
                'verbose_name': 'учебная группа',
                'verbose_name_plural': 'учебные группы',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.semester', verbose_name='Семестр')),
                ('subgroups', models.ManyToManyField(to='study.subgroup', verbose_name='Учебные группы')),
            ],
            options={
                'verbose_name': 'учебная дисциплина',
                'verbose_name_plural': 'учебная дисциплина',
            },
        ),
        migrations.CreateModel(
            name='StudentSubgroupStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('exp', 'Отчислен'), ('std', 'Учится'), ('fin', 'Закончил обучение')], default='std', max_length=4, verbose_name='Статус обучения')),
                ('student_number', models.CharField(max_length=64, verbose_name='Номер студенческого билета')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroup_statuses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_statuses', to='study.subgroup', verbose_name='Учебная группа')),
            ],
            options={
                'verbose_name': 'статус студента в учебной группе',
                'verbose_name_plural': 'статусы студентов в учебных группах',
                'unique_together': {('student', 'subgroup')},
            },
        ),
        migrations.CreateModel(
            name='TutorDisciplineStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('exp', 'Больше не работает'), ('m', 'Помощник преподавателя'), ('t', 'Преподаватель'), ('ht', 'Старший преподаватель')], default='t', max_length=4, verbose_name='Статус преподавания')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_statuses', to='study.discipline', verbose_name='Дисциплина')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_statuses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'статус преподавателя в дисциплине',
                'verbose_name_plural': 'статусы преподавателя в дисциплине',
                'unique_together': {('tutor', 'discipline')},
            },
        ),
    ]
