# Generated by Django 5.1.5 on 2025-05-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subgroup',
            old_name='subgroup_type',
            new_name='level',
        ),
        migrations.AlterField(
            model_name='discipline',
            name='subgroups',
            field=models.ManyToManyField(related_name='disciplines', to='study.subgroup', verbose_name='Учебные группы'),
        ),
    ]
