# Generated by Django 5.1.5 on 2025-05-29 12:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_rename_subgroup_type_subgroup_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subgroup',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='subgroups', through='study.StudentSubgroupStatus', to=settings.AUTH_USER_MODEL, verbose_name='Студенты'),
        ),
    ]
