# Generated by Django 5.1.5 on 2025-01-26 15:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('answer', models.TextField(max_length=2048, verbose_name='Ответ')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
            ],
            options={
                'verbose_name': 'часто задаваемый вопрос',
                'verbose_name_plural': 'часто задаваемые вопросы',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('steps_count', models.PositiveIntegerField(help_text='Поле для денормализации', verbose_name='Количество этапов')),
            ],
            options={
                'verbose_name': 'стадия сдачи работы',
                'verbose_name_plural': 'стадии сдач работ',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('max_possible_value', models.FloatField(blank=True, null=True, verbose_name='Максимально возможный результат')),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now, help_text='Работа получает особую пометку, если она сдана после этого срока', verbose_name='Дедлайн по этапу')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядковый номер стадии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steps', to='stages.stage', verbose_name='Стадия сдачи работы')),
            ],
            options={
                'verbose_name': 'этап сдачи работы',
                'verbose_name_plural': 'этапы сдач работ',
            },
        ),
        migrations.CreateModel(
            name='UserStepResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Результат')),
                ('is_after_deadline', models.BooleanField(default=False, verbose_name='Работа сдана после дедлайна этапа')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.step', verbose_name='Этап')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_step_results', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_step_results', to=settings.AUTH_USER_MODEL, verbose_name='Абитуриент')),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('tutors', models.ManyToManyField(related_name='work', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'тип работы',
                'verbose_name_plural': 'типы работ',
            },
        ),
        migrations.AddField(
            model_name='stage',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='stages.worktype', verbose_name='Тип работы'),
        ),
    ]
