server {
    listen 80;
    listen [::]:80;

    server_name kra.local;
    include /etc/nginx/kra-xbase.conf;

    location / {
        proxy_pass $kra;
        proxy_set_header Host $host;
    }

    location /static/ {
        proxy_pass $kra;
        access_log off;
    }

    location ~ /\.git.* {
       deny all;
    }
}
