[common]
SECRET_KEY:
SITE_URL: http://kra.localhost
DEBUG: True
DEBUG_TOOLBAR: True

[minio]
ACCESS_KEY: admin
SECRET_KEY: access_key
BUCKET_NAME: kra
ENDPOINT_URL: http://minio-kra.localhost
ENABLED: True

[redis_common]
password:
host: 127.0.0.1

[celery]
BROKER_URL: redis://:${redis_common:password}@${redis_common:host}/6
RESULT_BACKEND: redis://:${redis_common:password}@${redis_common:host}/6
REDBEAT_LOCATION: redis://:${redis_common:password}@${redis_common:host}/7
CELERY_BEAT_MAX_LOOP_INTERVAL: 5
