server {
    listen 80;
    listen [::]:80;

    server_name kra.localhost;

    include /etc/nginx/kra-xbase.conf;
    include /etc/nginx/kra-xlocations.conf;

    location ~ /\.git.* {
       deny all;
    }
}
