set $kra http://127.0.0.1:8888;

access_log /var/log/nginx/kra.localhost/access.log timed;
error_log /var/log/nginx/kra.localhost/error.log;
resolver 8.8.8.8;

add_header X X;

client_max_body_size 20M;

proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_pass_header Set-Cookie;
proxy_pass_header Cookie;
proxy_hide_header UserId;
proxy_buffering off;
