# Generated by Django 5.1.5 on 2025-03-14 21:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0001_initial'),
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now, help_text='Работа получает особую пометку, если она сдана после этого срока', verbose_name='Дедлайн по этапу')),
                ('sequence_number', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('work_score_percent', models.IntegerField(default=100, verbose_name='Процент от итогового балла')),
                ('file_settings', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='attachments.filessettings', verbose_name='Файловые настройки')),
            ],
            options={
                'verbose_name': 'стадия сдачи работы',
                'verbose_name_plural': 'стадии сдач работ',
            },
        ),
        migrations.CreateModel(
            name='StudentSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('comment', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Текстовый комментарий к ответу')),
                ('is_created_after_deadline', models.BooleanField(default=None, help_text='Если NULL, значит работа не сдана', null=True, verbose_name='Работа сдана после дедлайна стадии')),
                ('is_updated_after_deadline', models.BooleanField(default=None, help_text='Если NULL, значит работа не сдана', null=True, verbose_name='Работа обновлена после дедлайна стадии')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.stage', verbose_name='Стадия')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_step_results', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'ответ студента',
                'verbose_name_plural': 'ответы студентов',
            },
        ),
        migrations.CreateModel(
            name='TutorMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('value', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, max_length=2000, verbose_name='Текстовый комментарий к оценке')),
                ('is_solution_updated', models.BooleanField(default=False, verbose_name='Был ответ студента обновлен после оценки?')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.studentsolution', verbose_name='Ответ студента')),
                ('tutor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Оценивший преподаватель')),
            ],
            options={
                'verbose_name': 'оценка ответа преподавателем',
                'verbose_name_plural': 'оценки ответов преподавателями',
            },
        ),
        migrations.AddField(
            model_name='studentsolution',
            name='actual_tutor_mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stages.tutormark', verbose_name='Актуальная оценка'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('work_type', models.CharField(choices=[('vkr', 'ВКР'), ('coursework', 'Курсовая')], max_length=16, verbose_name='Тип работы')),
                ('discipline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study.discipline', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'тип работы',
                'verbose_name_plural': 'типы работ',
            },
        ),
        migrations.AddField(
            model_name='stage',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='stages.work', verbose_name='Работа'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsolution',
            unique_together={('student', 'stage')},
        ),
    ]
