# Generated by Django 5.1.5 on 2025-05-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutormark',
            old_name='tutor_id',
            new_name='tutor',
        ),
        migrations.RemoveField(
            model_name='studentsolution',
            name='actual_tutor_mark',
        ),
        migrations.RemoveField(
            model_name='studentsolution',
            name='is_updated_after_deadline',
        ),
        migrations.RemoveField(
            model_name='tutormark',
            name='is_solution_updated',
        ),
        migrations.AddField(
            model_name='studentsolution',
            name='attempt_number',
            field=models.IntegerField(default=0, verbose_name='Номер попытки'),
        ),
    ]
