# Generated by Django 5.1.5 on 2025-05-29 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_rename_tutor_id_tutormark_tutor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='discipline_id',
            new_name='discipline',
        ),
        migrations.AlterField(
            model_name='tutormark',
            name='value',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
    ]
