# Generated by Django 5.1.5 on 2025-03-14 21:23

import application.minio
import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilesSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_files_amount', models.PositiveIntegerField(default=1, help_text='Максимальное допустимое количество - 10', verbose_name='Максимальное количество файлов')),
                ('max_file_size', models.PositiveIntegerField(default=5, help_text='Максимальный допустимый размер - 20 MB', verbose_name='Максимальный размер одного файла в MB')),
                ('extensions', models.TextField(blank=True, help_text="Введите через запятую, указывая точки. БЕЗ символов '*', '.'!", null=True, verbose_name='Допустимые расширения файлов')),
            ],
            options={
                'verbose_name': 'параметры файлового решения',
                'verbose_name_plural': 'параметры файловых решений',
            },
        ),
        migrations.CreateModel(
            name='SolutionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено в')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано в')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
                ('file', models.FileField(max_length=255, storage=storages.backends.s3.S3Storage(), upload_to=application.minio.get_step_colution_file_path, verbose_name='Файл')),
                ('filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='Оригинальное имя файла')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Если 0, значит файл еще не был загружен', verbose_name='Размер файла')),
            ],
            options={
                'verbose_name': 'файлы прикрепленные студентами',
            },
        ),
    ]
