# Generated by Django 5.1.5 on 2025-01-26 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
            ],
            options={
                'verbose_name': 'учебная дисциплина',
                'verbose_name_plural': 'учебная дисциплина',
            },
        ),
        migrations.CreateModel(
            name='Subgroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно?')),
            ],
            options={
                'verbose_name': 'учебная группа',
                'verbose_name_plural': 'учебные группы',
            },
        ),
        migrations.CreateModel(
            name='StudentSubgroupStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('exp', 'Отчислен'), ('std', 'Учится'), ('fin', 'Закончил обучение')], default='std', max_length=16, verbose_name='Статус обучения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroup_statuses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_statuses', to='study.subgroup', verbose_name='Учебная группа')),
            ],
            options={
                'verbose_name': 'статус студента в учебной группе',
                'verbose_name_plural': 'статусы студентов в учебных группах',
                'unique_together': {('user', 'subgroup')},
            },
        ),
        migrations.CreateModel(
            name='TutorSubgroupStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('exp', 'Больше не работает'), ('m', 'Помощник преподавателя'), ('t', 'Преподаватель'), ('ht', 'Старший преподаватель')], default='t', max_length=16, verbose_name='Статус обучения')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_statuses', to='study.subgroup', verbose_name='Учебная группа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_statuses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'статус преподавателя в учебной группе',
                'verbose_name_plural': 'статусы преподавателя в учебных группах',
                'unique_together': {('user', 'subgroup')},
            },
        ),
    ]
